### PR TITLE
Changes in net_demo_installer script

### PR DESCRIPTION
**Pull request by gaurav-dalvi**
Currently we are hard coding docker version for centos. After this change it will take docker version from docker_version ansible variable.

### CODE REVIEW

**Comment by jojimt** [comment]
LGTM

**Comment by jainvipin** [comment]
@gaurav-dalvi - why not keep something as default, this would allow people to not force setting this variable. Something that should work as default.

**Comment by gaurav-dalvi** [comment]
@jainvipin : Default is 1.11.1
See here : https://github.com/contiv/demo/blob/master/net/net_demo_installer#L197

You dont have to set it every time unless you want to override whats there in the script.

**Comment by jainvipin** [comment]
LGTM

**Pull request merged**
