### PR TITLE
Fix ConfirmPrompt for clear option

### PR DESCRIPTION
**Pull request by dvavili**
Fix issue where "net_demo_installer -c" deletes everything without confirmation. Move ConfirmPrompt function definition before getOpts

### CODE REVIEW

**Comment by dvavili** [comment]
@jojimt @gaurav-dalvi PTAL

**Comment by dvavili** [comment]
@unclejack: PTAL as well

**Comment by unclejack** [comment]
LGTM

**Comment by gaurav-dalvi** [comment]
Verified it . We can merge this one.

**Pull request merged**
