### PR TITLE
Moving to latest ansible version to include ACI fixups

### PR DESCRIPTION
**Pull request by dvavili**
Updating to the ansible version that contains some ACI fixups

### CODE REVIEW

**Comment by jojimt** [comment]
`IMPORTANT: You need to specify ALL hosts you're adding to the cluster
           on he command line. Setting them up one at a time is not
           supported`
The above message needs to be modified. We no longer take command line arguments, right?

**Comment by jainvipin** [comment]
This change LGTM
@DivyaVavili - please take care of the comment @jojimt mentioned; I will merge soon after

**Comment by dvavili** [comment]
@jojimt @jainvipin: Addressed the comment

**Comment by jainvipin** [comment]
LGTM

**Pull request merged**
